symlink-sdk:
	mkdir -p vendor/sentry
	rm -rf vendor/sentry/sentry-laravel
	cd vendor/sentry && ln -sf ../../../.. sentry-laravel

	rm -rf vendor/sentry/sentry
	cd vendor/sentry && ln -sf ../../../../../sentry-php sentry
