<?php

namespace Sentry\Features;

use Sentry\Laravel\Tests\TestCase;
use Illuminate\Console\Scheduling\Event;

class ConsoleIntegrationTest extends TestCase
{
    public function setUp(): void
    {
        if (!method_exists(Event::class, 'flushMacros')) {
            $this->markTestSkipped('Macroable::flushMacros() is not available in this Laravel version.');
        }

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testArtisanCommandIsRegistered(): void
    {
        Event::flushMacros();

        $this->refreshApplication();

        $this->assertTrue(Event::hasMacro('sentryMonitor'));
    }

    public function testArtisanCommandIsRegisteredWithoutDsnSet(): void
    {
        Event::flushMacros();

        $this->resetApplicationWithConfig([
            'sentry.dsn' => null,
        ]);

        $this->assertTrue(Event::hasMacro('sentryMonitor'));
    }
}
